# Generated by bin/generate — do not edit.
#
# Built from: profiles/base.Brewfile
# Edit those, then run: mise run generate

# =============================================================================
# What belongs in this file
#
#   Homebrew  anything that must exist before mise does (git, curl, zsh, mise
#             itself), GUI applications, launchd services, system libraries.
#
#   mise      language runtimes, and any CLI whose version a project may need
#             to pin. Declared per project in mise.toml, or globally in
#             ~/.config/mise/config.toml.
#
# Never both. Two managers for one tool means two installed versions and one
# of them silently shadowing the other on PATH.
# =============================================================================

# Options
# @icon:cog
cask_args quarantine: false

# Terminal & Shell
# @icon:terminal
brew "zsh"                  # Modern shell
brew "bash"                 # Latest bash version
brew "tmux"                 # Terminal multiplexer
brew "neovim"               # Modern vim
brew "starship"             # Cross-shell prompt
brew "zoxide"               # Smarter cd command
brew "chezmoi"              # Dotfiles manager
brew "thefuck"              # Correct previous command
brew "atuin"                # Shell history search

# Modern CLI Tools
# @icon:code
brew "bat"                  # cat with syntax highlighting
brew "eza"                  # ls replacement
brew "fd"                   # find replacement
brew "ripgrep"              # grep replacement
brew "fzf"                  # Fuzzy finder
brew "tree"                 # Directory tree view
brew "btop"                 # Resource monitor
brew "dust"                 # du replacement
brew "duf"                  # df replacement
brew "procs"                # ps replacement
brew "jq"                   # JSON processor
brew "yq"                   # YAML processor
brew "tlrc"                 # tldr pages client
brew "coreutils"            # GNU core utilities
brew "sd"                   # sed replacement
brew "hyperfine"            # Benchmarking tool
brew "tokei"                # Code statistics
brew "xh"                   # HTTPie replacement

# System Utilities
# @icon:wrench
brew "fastfetch"            # System info display
brew "nmap"                 # Network scanner
brew "trash"                # Safe rm replacement
brew "curl"                 # Newer than the system one
brew "wget"                 # Recursive downloader
brew "openssh"              # Newer than the system one
brew "unar"                 # Archive extraction (CLI)

# Git & Version Control
# @icon:git
brew "git"                  # Version control
brew "git-delta"            # Better git diff
brew "lazygit"              # Git TUI
brew "gh"                   # GitHub CLI
brew "git-lfs"              # Large file storage
brew "gitleaks"             # Git secrets scanner
brew "git-filter-repo"      # History rewriting

# Security & Privacy
# @icon:shield
brew "gnupg"                # GPG encryption
brew "git-crypt"            # Git file encryption
brew "age"                  # Modern encryption
brew "sops"                 # Secrets management
brew "lynis"                # Security auditing
brew "trivy"                # Container scanner

# Development Tools
# @icon:tools
# Language runtimes (rust, node, python, ruby, ...) are not installed here.
# They are mise's job: `mise use rust@latest` in a project, or in the global
# ~/.config/mise/config.toml.
#
# shellcheck and shfmt are absent on purpose: this repository pins them in its
# own mise.toml, so installing them here too meant two copies of each, with
# Homebrew's winning on PATH. That file is tracked, so nothing is lost.
#
# Other CLIs stay with Homebrew even where a project might want to pin them.
# A mise tool is only on PATH once mise activates, and the global mise config
# is not version-controlled today — moving a tool there would trade a tracked
# declaration for an untracked one. See "Tools managed by mise" in the README.
brew "mise"                 # Polyglot runtime manager (bootstraps the rest)
brew "direnv"               # Per-directory env vars
brew "watchman"             # File watcher
brew "biome"                # Fast JS/TS linter & formatter
brew "uv"                   # Python package manager
brew "gum"                  # Elegant shell scripts
brew "mas"                  # Mac App Store CLI
brew "pre-commit"           # Git hooks manager
brew "act"                  # Run GitHub Actions locally
brew "cmake"                # Build system
brew "pkgconf"              # Build flag helper
brew "rtk"                  # Token-optimised CLI proxy

# Databases
# @icon:database
# Database *servers* live in the work profile: they run as launchd services and
# are only wanted on a machine that needs them. sqlite is a library, not a
# service, so it stays here.
brew "sqlite"               # Lightweight database

# Productivity Apps
# @icon:rocket
cask "raycast"              # Spotlight replacement
cask "notion"               # Notes & docs
cask "hiddenbar"            # Menu bar manager
cask "bitwarden"            # Password manager

# Development Apps
# @icon:apps
cask "ghostty"              # Terminal emulator
cask "visual-studio-code"   # Code editor
cask "docker-desktop"       # Containers
brew "lazydocker"           # Docker TUI
cask "bruno"                # API client
cask "zen"                  # Privacy browser
cask "google-chrome"        # Cross-browser testing
cask "firefox"              # Cross-browser testing
cask "tableplus"            # Database GUI
cask "claude"               # Claude AI desktop app

# Utility Apps
# @icon:puzzle
cask "alt-tab"              # Windows-style alt-tab
cask "gas-mask"             # Hosts file manager
cask "utm"                  # Virtual machines
cask "the-unarchiver"       # Archive extraction
cask "appcleaner"           # App uninstaller
cask "stats"                # System monitor menubar
cask "kap"                  # Screen recorder GIF/MP4
cask "scroll-reverser"      # Reverse scroll per device

# Media & Creative
# @icon:video
brew "imagemagick"          # Image manipulation
brew "ffmpeg"               # Video/audio processing
brew "yt-dlp"               # Video downloader

# Fonts
# @icon:font
cask "font-fira-code-nerd-font"       # Fira Code + icons
cask "font-jetbrains-mono-nerd-font"  # JetBrains Mono + icons
cask "font-hack-nerd-font"            # Hack + icons
cask "font-meslo-lg-nerd-font"        # Meslo + icons
